all		:

00		:
		cc -Wall -Wextra -Werror 00_pipex.c -o _unix 
		@echo -e
		@./_unix

01		:
		cc -Wall -Wextra -Werror 01_pipex.c -o _unix 
		@echo -e
		@./_unix

02		:
		cc -Wall -Wextra -Werror 02_pipex.c -o _unix 
		@echo -e
		@./_unix

03		:
		cc -Wall -Wextra -Werror 03_pipex.c -o _unix 
		@echo -e
		@./_unix

04		:
		cc -Wall -Wextra -Werror 04_pipex.c -o _unix 
		@echo -e
		@./_unix

05		:
		cc -Wall -Wextra 05_pipex.c -o _unix 
		@echo -e
		@./_unix

06		:
		cc -Wall -Wextra -Werror 06_pipex.c -o _unix 
		@echo -e
		@./_unix

07		:
		cc -Wall -Wextra -Werror 07_pipex.c -o _unix 
		@echo -e
		@./_unix

fclean	:
		rm *unix

.PHONY	: all fclean
