all		:

00		:
		cc -Wall -Wextra -Werror 00_pipex.c -o _unix 
		@echo "\n"
		@./_unix

01		:
		cc -Wall -Wextra -Werror 01_pipex.c -o _unix 
		@echo "\n"
		@./_unix

02		:
		cc -Wall -Wextra -Werror 02_pipex.c -o _unix 
		@echo "\n"
		@./_unix

03		:
		cc -Wall -Wextra -Werror 03_pipex.c -o _unix 
		@echo "\n"
		@./_unix

04		:
		cc -Wall -Wextra -Werror 04_pipex.c -o _unix 
		@echo "\n"
		@./_unix

fclean	:
		rm *unix

.PHONY	: all fclean
